name: "Debian Workflow"

inputs:
  VERSION_NAME:
    description: 'Version Name to be used for build'
    required: false
    default: '1.0.0'
  VERSION_CODE:
    description: 'Version Code to be used for build'
    required: true
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        flutter-version-file: pubspec.yaml

    - name: Install Linux dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          liblzma-dev \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          libblkid-dev \
          libgcrypt20-dev

    - name: Build Linux (Debian) App
      shell: bash
      env:
        VERSION_NAME: ${{ inputs.VERSION_NAME }}
        VERSION_CODE: ${{ inputs.VERSION_CODE }}
      run: |
        flutter build linux --build-name $VERSION_NAME --build-number $VERSION_CODE